### ISSUE TITLE
关于我被绑去中科大做学渣样本的事 - Goddess Unknown

### ISSUE THREAD

**Issue by noirgif** [noirgif/blog#13]
https://www.nir.moe/posts/keda-sample/ 

 60分刚好，一分不多，一分不少。 虽然有一种想把这句话当作座右铭的冲动，但是我明白对我来说，这充其量只是高考考了450的自嘲罢了。 网上翻了翻过去学校的分数线，在450附近的，感觉南阳理工学院还不错。学校录不少人，而且名字也好听。以后可以跟同学吹，自己是南阳理工的，反正他们十有八九也没听说过这个学校。 我躺在沙发上，幻想着多年以后高中同学会上的情形。六月下旬的太阳还是一如既往的毒辣，蝉还在外面聒噪

**Comment by userid** [comment]
都忘了东区是什么样子了

**Comment by noirgif** [comment]
> @userid
> 都忘了东区是什么样子了

233，我要趁我记得的时候赶紧写完
